# ------------------------------------------------Global Paths------------------------------------------------#
# Paths to models
model2path:
  e5: "YOUR_MODEL_PATH"
  bge: "BAAI/bge-base-en-v1.5"
  contriever: "facebook/contriever"
  llama2-7B-chat: "YOUR_MODEL_PATH"
  llama2-13B-chat: "YOUR_MODEL_PATH"
  llama3-8B-instruct: "YOUR_MODEL_PATH"

# Pooling methods for each embedding model
model2pooling:
  e5: "mean"
  bge: "cls"
  contriever: "mean"
  jina: "mean"
  dpr: "cls"

# Indexes path for retrieval models
method2index:
  e5: "YOUR_INDEX_PATH"
  bm25: "YOUR_INDEX_PATH"
  contriever: ~

# ------------------------------------------------Environment Settings------------------------------------------------#
# Directory paths for data and outputs
data_dir: "datasets/"
save_dir: "output/"
log_info: []

gpu_id: "0,1,2,3"
dataset_name: "default" # name of the dataset in data_dir
split: ["test"]  # dataset split to load (e.g. train,dev,test)

# Sampling configurations for testing
test_sample_num: ~  # number of samples to test (only work in dev/test split), if None, test all samples
random_sample: False # whether to randomly sample the test samples

# Seed for reproducibility
# default: 2024
seed: 2019

# Whether save intermediate data
save_intermediate_data: True
save_note: "experiment"

# -------------------------------------------------Retrieval Settings------------------------------------------------#
# If set the name, the model path will be find in global paths
retrieval_method: "bm25"  # name or path of the retrieval model.
retrieval_model_path: ~ # path to the retrieval model

index_path: "YOUR_INDEX_PATH" # set automatically if not provided.
faiss_gpu: False # whether use gpu to hold index
corpus_path: ~  # path to corpus in '.jsonl' format that store the documents
bm25_backend: "bm25s"

use_sentence_transformer: False
retrieval_topk: 100 # number of retrieved documents
retrieval_batch_size: 256  # batch size for retrieval
retrieval_use_fp16: True  # whether to use fp16 for retrieval model
retrieval_query_max_length: 128  # max length of the query
save_retrieval_cache: False # whether to save the retrieval cache
use_retrieval_cache: False # whether to use the retrieval cache
retrieval_cache_path: ~ # path to the retrieval cache
retrieval_pooling_method: ~ # set automatically if not provided

use_reranker: True # whether to use reranker
rerank_model_name: "e5" # same as retrieval_method
rerank_model_path: ~ # path to reranker model, path will be automatically find in `retriever_model2path`
rerank_pooling_method: ~
rerank_topk: 5  # number of remain documents after reranking
rerank_max_length: 512
rerank_batch_size: 256 # batch size for reranker
rerank_use_fp16: True

# -------------------------------------------------Generator Settings------------------------------------------------#
framework: hf # inference frame work of LLM, supporting: 'hf','vllm','fschat'
generator_model: "llama3-8B-instruct" # name or path of the generator model
generator_model_path: ~

generator_max_input_len: 1024  # max length of the input
generator_batch_size: 4 # batch size for generation, invalid for vllm
generation_params:
  do_sample: False
  max_tokens: 32

openai_setting:
  base_url: "YOUR_URL"
  api_key: "YOUR_KEY"

use_fid: False # whether to use FID, only valid in encoder-decoder model
gpu_memory_utilization: 0.85 # ratio of gpu's memory usage for generator

# -------------------------------------------------Evaluation Settings------------------------------------------------#
# Metrics to evaluate the result
metrics: ["em", "f1", "acc"]

# Specify setting for metric, will be called within certain metrics
metric_setting:
  retrieval_recall_topk: 5
  tokenizer_name: "gpt-4"

save_metric_score: True #　whether to save the metric score into txt file